model:
  model_path: /mnt/local/localcache00/Qwen3-VL-2B-Instruct
  attn_implementation: flash_attention_2

data:
  train_path: unused
  libero_data_dir: /mnt/local/localcache00/hf_libero
  libero_dataset_backend: lerobot
  obs_len: 4
  pred_len: 2
  max_seq_len: 2048

train:
  output_dir: /mnt/local/localcache00/qwen3_vl_libero
  dyn_bsz: false
  data_parallel_mode: fsdp2
  rmpad_with_pos_ids: true
  use_wandb: false
  wandb_project: qwen3_vl_libero
  wandb_name: qwen3_vl_libero
  ulysses_parallel_size: 1
  freeze_vit: false
  vit_lr: 1.0e-6
  lr: 1.0e-4
  lr_decay_style: cosine
  lr_warmup_ratio: 0.03
  num_train_epochs: 1
  micro_batch_size: 8
  global_batch_size: 64
  max_grad_norm: 1.0
  init_device: meta
  enable_profiling: false
  ckpt_manager: dcp
  save_hf_weights: true
  save_epochs: 5
  max_steps: 50
