"""Shared fixtures for LIBERO dataset tests.

Provides a session-scoped synthetic LIBERO dataset fixture that creates
a minimal episode-per-file dataset in a temporary directory, suitable for
integration tests that need parquet data without the real dataset mount.
"""

import json
import tempfile

import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq
import pytest


def _write_synthetic_episode_parquet(
    path: str,
    num_rows: int,
    episode_index: int,
    rng: np.random.RandomState,
) -> None:
    """Write a minimal parquet file mimicking LIBERO episode-per-file layout.

    Schema matches the real LIBERO dataset:
    - state: fixed_size_list<float32>[8]
    - actions: fixed_size_list<float32>[7]
    - image: struct<bytes: binary, path: string>
    - frame_index: int64
    - episode_index: int64

    Uses plain (non-dict-encoded) columns to avoid Rust reader panics.

    Args:
        path: Output parquet file path.
        num_rows: Number of rows (frames) in the episode.
        episode_index: Episode index for metadata columns.
        rng: Seeded random state for deterministic data.
    """
    # State: fixed_size_list<float32>[8]
    state_flat = rng.randn(num_rows * 8).astype(np.float32)
    state_data = pa.FixedSizeListArray.from_arrays(
        pa.array(state_flat),
        list_size=8,
    )

    # Actions: fixed_size_list<float32>[7]
    action_flat = rng.randn(num_rows * 7).astype(np.float32)
    action_data = pa.FixedSizeListArray.from_arrays(
        pa.array(action_flat),
        list_size=7,
    )

    # Image: struct<bytes: binary, path: string>
    # Valid 1x1 white RGB PNG generated by Pillow
    png_bytes = (
        b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01"
        b"\x00\x00\x00\x01\x08\x02\x00\x00\x00\x90wS\xde\x00"
        b"\x00\x00\x0cIDATx\x9cc\xf8\xff\xff?\x00\x05\xfe\x02"
        b"\xfe\r\xefF\xb8\x00\x00\x00\x00IEND\xaeB`\x82"
    )
    image_bytes = pa.array([png_bytes] * num_rows, type=pa.binary())
    image_paths = pa.array(
        [f"ep{episode_index}/frame_{i}.png" for i in range(num_rows)],
        type=pa.string(),
    )
    image_struct = pa.StructArray.from_arrays(
        [image_bytes, image_paths],
        names=["bytes", "path"],
    )

    table = pa.table(
        {
            "image": image_struct,
            "state": state_data,
            "actions": action_data,
            "frame_index": pa.array(list(range(num_rows)), type=pa.int64()),
            "episode_index": pa.array([episode_index] * num_rows, type=pa.int64()),
        }
    )

    # Write with plain encoding (no dictionary) to avoid Rust reader panics.
    # write_page_index=True is required for the youmu Rust reader's offset index.
    pq.write_table(
        table,
        path,
        use_dictionary=False,
        write_page_index=True,
    )


@pytest.fixture(scope="session")
def synthetic_libero_dir():
    """Create a minimal synthetic LIBERO dataset in a temp directory.

    Layout:
        <tmpdir>/
            data/chunk-000/
                episode_000000.parquet  (5 rows)
                episode_000001.parquet  (7 rows)
                episode_000002.parquet  (10 rows)
            meta/
                episodes.jsonl

    Parquet schema matches the real LIBERO dataset:
    - state: fixed_size_list<float32>[8]
    - actions: fixed_size_list<float32>[7]
    - image: struct<bytes: binary, path: string>
    - frame_index: int64
    - episode_index: int64

    Returns:
        str: Path to the temporary dataset directory.
    """
    rng = np.random.RandomState(seed=42)
    episode_lengths = {0: 5, 1: 7, 2: 10}

    with tempfile.TemporaryDirectory(prefix="synthetic_libero_") as tmpdir:
        # Create directory structure
        data_dir = f"{tmpdir}/data/chunk-000"
        meta_dir = f"{tmpdir}/meta"
        import os

        os.makedirs(data_dir)
        os.makedirs(meta_dir)

        # Write episode parquet files
        for ep_idx, length in episode_lengths.items():
            fpath = f"{data_dir}/episode_{ep_idx:06d}.parquet"
            _write_synthetic_episode_parquet(fpath, length, ep_idx, rng)

        # Write episodes.jsonl metadata
        jsonl_path = f"{meta_dir}/episodes.jsonl"
        with open(jsonl_path, "w") as f:
            for ep_idx, length in episode_lengths.items():
                json.dump(
                    {
                        "episode_index": ep_idx,
                        "tasks": [f"synthetic task {ep_idx}"],
                        "length": length,
                    },
                    f,
                )
                f.write("\n")

        yield tmpdir
